build:
  environment:
    variables:
      XDEBUG_MODE: coverage
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=tests/reports/coverage-clover.xml'
        coverage:
          file: 'tests/reports/coverage-clover.xml'
          format: 'clover'
